name: MSF-WSI
channels:
  - pytorch
  - bioconda
  - nvidia
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - pytorch-cuda=11.8
  - torchvision
  - albumentations
  - scikit-image
  - torchmetrics
  - matplotlib
  - tqdm
  - wandb
  - tensorboard
  - monai
  - cucim
  - cudatoolkit=11.8
  - tifffile
  - pip:
    - segmentation-models-pytorch>=0.3.2
    - torch-tb-profiler==0.4.1
    - yacs==0.1.8